name: Build and publish

on:
  release:
    types: [published]

jobs:
  build:
    name: Push to Steam Workshop
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Copy to /dist
        run: find . -maxdepth 1 -type d -not -path "./dist" -not -path "." -not -path "./.*" -exec mv --target-directory "./dist" {} +

      - name: Add files to Github release
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo "$GITHUB_CONTEXT"
          exit 1

      # Upload to Steam Workshop
      - name: Upload to Steam Workshop
        uses: arma-actions/workshop-upload@v1
        with:
          appId: '387990'
          itemId: '2448492759' # Id of item to update
          contentPath: 'dist'
          changelog: ''
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
