name: Build and publish

on:
  release:
    types: [published]

jobs:
  build:
    name: Push to Steam Workshop
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Copy to /dist
        run: find . -maxdepth 1 -type d -not -path "./dist" -not -path "." -not -path "./.*" -exec mv --target-directory "./dist" {} +

      - name: Add files to Github release
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: |
          echo '{"version": "${{ github.event.release.tag_name }}"}' > ./dist/version.json
          (cd ./dist && zip -r ../dist.zip .)
          echo "$GITHUB_CONTEXT"

      - name: Upload Release Asset
        id: upload-release-asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./release.zip
          asset_name: ${{ github.event.repository.name }}-${{ github.event.release.tag_name }}.zip
          asset_content_type: application/zip

      # Upload to Steam Workshop
      - name: Upload to Steam Workshop
        uses: arma-actions/workshop-upload@v1
        with:
          appId: '387990'
          itemId: '2448492759' # Id of item to update
          contentPath: 'dist'
          changelog: "[b]${{ github.event.release.tag_name }}[/b]\n\n${{ github.event.release.body }}\n\n${{ github.event.release.html_url }}"
        env:
          STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
          STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
